service: MinAppBackend

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  stage: dev
  environment:
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    REGION: ${env:REGION}
    RESERVATIONS_TABLE: ${env:RESERVATIONS_TABLE}
    USERS_TABLE: ${env:USERS_TABLE}
    NOTIFICATIONS_TABLE: ${env:NOTIFICATIONS_TABLE}
    MESSAGES_TABLE: ${env:MESSAGES_TABLE}
    USERS_TABLE_PRIMARY_KEY: ${env:USERS_TABLE_PRIMARY_KEY}
    CORS_ORIGIN: ${env:CORS_ORIGIN}

functions:
  register:
    handler: src/handlers/auth.register
    events:
      - http:
          path: auth/register
          method: post
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  login:
    handler: src/handlers/auth.login
    events:
      - http:
          path: auth/login
          method: post
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  getUsers:
    handler: src/handlers/users.getUsers
    events:
      - http:
          path: users
          method: get
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  createNotification:
    handler: src/handlers/notifications.createNotification
    events:
      - http:
          path: notifications
          method: post
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  getNotifications:
    handler: src/handlers/notifications.getNotifications
    events:
      - http:
          path: notifications
          method: get
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  deleteNotification:
    handler: src/handlers/notifications.deleteNotification
    events:
      - http:
          path: notifications/{id}
          method: delete
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  createReservation:
    handler: src/handlers/reservations.createReservation
    events:
      - http:
          path: reservations
          method: post
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  getReservations:
    handler: src/handlers/reservations.getReservations
    events:
      - http:
          path: reservations
          method: get
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  deleteReservation:
    handler: src/handlers/reservations.deleteReservation
    events:
      - http:
          path: reservations/delete
          method: post
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  sendMessage:
    handler: src/handlers/messages.sendMessage
    events:
      - http:
          path: messages/send
          method: post
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  getMessages:
    handler: src/handlers/messages.getMessages
    events:
      - http:
          path: messages
          method: get
          cors:
            origin: 'http://localhost:3000'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

plugins:
  - serverless-offline
